import { createContext, useContext, useState, useEffect, type ReactNode } from 'react';
import type { Language } from '@/types/types';

// ─── Comprehensive translation dictionary ────────────────────────────────────
const translations: Record<Language, Record<string, string>> = {
  en: {
    home: "Home",
    about_us: "About Us",
    privacy_policy: "Privacy Policy",
    find_my_car: "Car Request Form",
    inventory: "Inventory",
    auctions: "Auctions",
    sellYourCar: "Sell Your Car",
    blog: "Blog",
    contact: "Contact",
    login: "Login",
    register: "Register",
    logout: "Logout",
    dashboard: "Dashboard",
    admin: "Admin Panel",
    dealership: "Dealership Portal",
    backToSite: "Back to Site",
    searchPlaceholder: "Search by make, model, keyword...",
    search: "Search",
    searchCars: "Search Cars",
    aiSearch: "AI Search",
    tryAiSearch: "Try AI Search",
    aiSearchPlaceholder: "e.g. red SUV under 30 lakhs in Karachi...",
    featuredCars: "Featured Cars",
    latestListings: "Latest Listings",
    browseByBrand: "Browse By Brand",
    browseByType: "Browse by Type",
    liveAuctions: "Live Auctions",
    whyChooseUs: "Why Choose Us",
    newsletter: "Newsletter",
    newsletterSubtitle: "Subscribe for the latest cars, auctions, and automotive news.",
    subscribe: "Subscribe",
    enterEmail: "Enter your email",
    heroSubtitle: "Discover thousands of verified cars from trusted dealerships across Pakistan.",
    heroCta: "Explore Inventory",
    heroAuctionCta: "Live Auctions",
    discoverCars: "Discover Cars",
    premiumExperience: "Premium Experience",
    totalCars: "Total Cars",
    totalUsers: "Total Users",
    totalAuctions: "Auctions Completed",
    totalSales: "Happy Customers",
    listedCars: "Listed Cars",
    verifiedDealers: "Verified Dealers",
    satisfiedCustomers: "Satisfied Customers",
    citiesCovered: "Cities Covered",
    viewAll: "View All",
    viewDetails: "View Details",
    viewMore: "View More",
    compare: "Compare",
    addToWishlist: "Add to Wishlist",
    removeFromWishlist: "Remove from Wishlist",
    price: "Price",
    year: "Year",
    mileage: "Mileage",
    fuelType: "Fuel Type",
    transmission: "Transmission",
    color: "Color",
    bodyType: "Body Type",
    condition: "Condition",
    location: "Location",
    city: "City",
    registrationCity: "Registration City",
    engineCapacity: "Engine Capacity",
    doors: "Doors",
    seatingCapacity: "Seating",
    assembly: "Assembly",
    features: "Features",
    description: "Description",
    specifications: "Specifications",
    similarCars: "Similar Cars",
    contactSeller: "Contact Seller",
    whatsappChat: "WhatsApp Chat",
    makeInquiry: "Make Inquiry",
    callNow: "Call Now",
    negotiable: "Negotiable",
    imported: "Imported",
    local: "Local Assembly",
    filters: "Filters",
    clearFilters: "Clear Filters",
    applyFilters: "Apply Filters",
    sortBy: "Sort By",
    latest: "Latest",
    lowestPrice: "Lowest Price",
    highestPrice: "Highest Price",
    mostViewed: "Most Viewed",
    minPrice: "Min Price",
    maxPrice: "Max Price",
    minYear: "Min Year",
    maxYear: "Max Year",
    allBrands: "All Brands",
    allTypes: "All Types",
    allCities: "All Cities",
    allConditions: "All Conditions",
    allTransmissions: "All Transmissions",
    priceRange: "Price Range",
    yearRange: "Year Range",
    sold: "Sold",
    available: "Available",
    reserved: "Reserved",
    pending: "Pending",
    pendingApproval: "Pending Approval",
    draft: "Draft",
    scheduled: "Scheduled",
    ended: "Ended",
    active: "Active",
    inactive: "Inactive",
    approved: "Approved",
    rejected: "Rejected",
    featured: "Featured",
    endingInText: "Ending In",
    currentBid: "Current Bid",
    startingBid: "Starting Bid",
    placeBid: "Place Bid",
    bidNow: "Bid Now",
    reservePrice: "Reserve Price",
    bidHistory: "Bid History",
    myBids: "My Bids",
    proxyBid: "Proxy Bid",
    depositRequired: "Deposit Required",
    auctionEnded: "Auction Ended",
    watchlist: "Watchlist",
    addToWatchlist: "Add to Watchlist",
    hours: "Hours",
    minutes: "Minutes",
    seconds: "Seconds",
    days: "Days",
    bidIncrement: "Bid Increment",
    winner: "Winner",
    noActiveAuctions: "No active auctions at the moment.",
    name: "Name",
    email: "Email",
    phone: "Phone",
    message: "Message",
    subject: "Subject",
    send: "Send",
    sending: "Sending...",
    submit: "Submit",
    save: "Save",
    saving: "Saving...",
    cancel: "Cancel",
    confirm: "Confirm",
    delete: "Delete",
    edit: "Edit",
    add: "Add",
    update: "Update",
    upload: "Upload",
    brand: "Brand",
    model: "Model",
    variant: "Variant",
    selectBrand: "Select Brand",
    selectModel: "Select Model",
    selectVariant: "Select Variant",
    selectYear: "Select Year",
    selectColor: "Select Color",
    selectCity: "Select City",
    selectCondition: "Select Condition",
    selectBodyType: "Select Body Type",
    selectTransmission: "Select Transmission",
    selectFuelType: "Select Fuel Type",
    addImages: "Add Images",
    uploadImages: "Upload Images",
    maxImages: "Max 10 images",
    generateDescription: "Generate AI Description",
    priceSuggestion: "Get Price Suggestion",
    required: "Required",
    optional: "Optional",
    titleLabel: "Listing Title",
    chassisNumber: "Chassis Number",
    registrationYear: "Registration Year",
    sellCarTitle: "Sell Your Car",
    sellCarSubtitle: "List your vehicle on Pakistan's premier automotive marketplace.",
    listingDetails: "Listing Details",
    vehicleInfo: "Vehicle Information",
    contactInfo: "Contact Information",
    reviewSubmit: "Review & Submit",
    basicInfo: "Basic Info",
    pricingMileage: "Pricing & Mileage",
    readMore: "Read More",
    publishedOn: "Published on",
    author: "Author",
    categories: "Categories",
    tags: "Tags",
    relatedArticles: "Related Articles",
    latestNews: "Latest News",
    allPosts: "All Posts",
    searchArticles: "Search articles...",
    shareArticle: "Share Article",
    backToBlog: "Back to Blog",
    getInTouch: "Get In Touch",
    contactSubtitle: "We're here to help you find your perfect vehicle or answer any questions.",
    contactInfo2: "Contact Information",
    address: "Address",
    openInMaps: "Open in Maps",
    businessHours: "Business Hours",
    officeHours: "Mon–Sat: 9am – 7pm",
    messageSent: "Message Sent!",
    messageSentDesc: "We'll get back to you within 24 hours.",
    myProfile: "My Profile",
    mySavedCars: "Saved Cars",
    myInquiries: "My Inquiries",
    notifications: "Notifications",
    accountSettings: "Account Settings",
    profilePhoto: "Profile Photo",
    changePassword: "Change Password",
    savedSearches: "Saved Searches",
    activityHistory: "Activity History",
    dealershipDashboard: "Dealership Dashboard",
    inventoryManagement: "Inventory Management",
    addNewCar: "Add New Car",
    editListing: "Edit Listing",
    deleteListing: "Delete Listing",
    leadsAndCRM: "Leads & CRM",
    salesTransactions: "Sales & Transactions",
    teamManagement: "Team Management",
    analytics: "Analytics",
    activityLog: "Activity Log",
    communication: "Communication",
    adminDashboard: "Admin Dashboard",
    userManagement: "User Management",
    dealershipManagement: "Dealership Management",
    auctionManagement: "Auction Management",
    contentManagement: "Content Management",
    vehicleDatabase: "Vehicle Database",
    brandSettings: "Brand Settings",
    seoSettings: "SEO Settings",
    themeCustomizer: "Theme Customizer",
    testimonialsMgmt: "Testimonials Management",
    heroBanner: "Hero Banner",
    homepageSections: "Homepage Sections",
    brandCarousel: "Brand Carousel",
    imageCompression: "Image Compression",
    inquiryManagement: "Inquiry Management",
    blogManagement: "Blog Management",
    listingModeration: "Listing Moderation",
    reports: "Reports",
    performance: "Performance",
    contactDisplay: "Contact Display",
    adminContact: "Admin Contact",
    dealerContact: "Dealer Contact",
    vehicleDatabaseTitle: "Vehicle Database Management",
    addBrand: "Add Brand",
    addModel: "Add Model",
    addVariant: "Add Variant",
    editBrand: "Edit Brand",
    editModel: "Edit Model",
    editVariant: "Edit Variant",
    deleteBrand: "Delete Brand",
    deleteModel: "Delete Model",
    deleteVariant: "Delete Variant",
    importJson: "Import JSON",
    jsonImport: "JSON Import",
    pasteJson: "Paste JSON data",
    importFromJson: "Import from JSON",
    downloadTemplate: "Download Template",
    duplicateFound: "Duplicate Found",
    duplicateSkipped: "Duplicate entries skipped",
    importSuccess: "Import successful",
    countryOfOrigin: "Country of Origin",
    japaneseBreands: "Japanese Brands",
    chineseBrands: "Chinese Brands",
    pakistaniBrands: "Pakistani Brands",
    siteLogo: "Site Logo",
    siteFavicon: "Site Favicon",
    uploadLogo: "Upload Logo",
    uploadFavicon: "Upload Favicon",
    logoPreview: "Logo Preview",
    faviconPreview: "Favicon Preview",
    currentLogo: "Current Logo",
    logoUpdated: "Logo updated successfully",
    faviconUpdated: "Favicon updated successfully",
    imageConvertedWebp: "Image auto-converted to WebP",
    quickLinks: "Quick Links",
    contactUs: "Contact Us",
    followUs: "Follow Us",
    copyright: "© 2025 XYZ Automobiles. All rights reserved.",
    loading: "Loading...",
    noResults: "No results found",
    error: "Error",
    retry: "Retry",
    goHome: "Go Home",
    pageNotFound: "Page Not Found",
    backToHome: "Back to Home",
    darkMode: "Dark Mode",
    lightMode: "Light Mode",
    language: "Language",
    currency: "Currency",
    settings: "Settings",
    profile: "Profile",
    help: "Help",
    about: "About",
    privacyPolicy: "Privacy Policy",
    termsOfService: "Terms of Service",
    allRightsReserved: "All Rights Reserved",
    pkr: "PKR",
    lac: "Lac",
    crore: "Crore",
    thousand: "Thousand",
    new: "New",
    used: "Used",
    certifiedPreOwned: "Certified Pre-Owned",
    petrol: "Petrol",
    diesel: "Diesel",
    hybrid: "Hybrid",
    electric: "Electric",
    automatic: "Automatic",
    manual: "Manual",
    cvt: "CVT",
    sedan: "Sedan",
    suv: "SUV",
    hatchback: "Hatchback",
    van: "Van",
    truck: "Truck",
    coupe: "Coupe",
    convertible: "Convertible",
    wagon: "Wagon",
    testimonials: "testimonials",
    heroTitle: "heroTitle",
    footerDesc: "footerDesc",
  },

  ur: {
    home: "ہوم",
    about_us: "ہمارے بارے میں",
    privacy_policy: "رازداری کی پالیسی",
    find_my_car: "گاڑی کی درخواست فارم",
    inventory: "انوینٹری",
    auctions: "نیلامی",
    sellYourCar: "اپنی گاڑی بیچیں",
    blog: "بلاگ",
    contact: "رابطہ",
    login: "لاگ ان",
    register: "رجسٹر",
    logout: "لاگ آؤٹ",
    dashboard: "ڈیش بورڈ",
    admin: "ایڈمن پینل",
    dealership: "ڈیلرشپ پورٹل",
    backToSite: "سائٹ پر واپس جائیں",
    searchPlaceholder: "میک، ماڈل یا کی ورڈ سے تلاش کریں...",
    search: "تلاش",
    searchCars: "گاڑیاں تلاش کریں",
    aiSearch: "اے آئی تلاش",
    tryAiSearch: "اے آئی تلاش آزمائیں",
    aiSearchPlaceholder: "مثال: کراچی میں 30 لاکھ سے کم کی سرخ ایس یو وی...",
    featuredCars: "نمایاں گاڑیاں",
    latestListings: "تازہ ترین اشتہارات",
    browseByBrand: "برانڈ کے مطابق",
    browseByType: "قسم کے مطابق",
    liveAuctions: "لائیو نیلامی",
    whyChooseUs: "ہمیں کیوں منتخب کریں",
    newsletter: "نیوزلیٹر",
    newsletterSubtitle: "تازہ ترین گاڑیوں اور نیلامیوں کے لیے سبسکرائب کریں۔",
    subscribe: "سبسکرائب",
    enterEmail: "ای میل درج کریں",
    heroSubtitle: "پاکستان بھر کے قابل اعتماد ڈیلرشپس سے ہزاروں تصدیق شدہ گاڑیاں دریافت کریں۔",
    heroCta: "گاڑیاں دیکھیں",
    heroAuctionCta: "لائیو نیلامی",
    discoverCars: "گاڑیاں دریافت کریں",
    premiumExperience: "پریمیم تجربہ",
    totalCars: "کل گاڑیاں",
    totalUsers: "کل صارفین",
    totalAuctions: "مکمل نیلامیاں",
    totalSales: "خوش گاہک",
    listedCars: "درج گاڑیاں",
    verifiedDealers: "تصدیق شدہ ڈیلرز",
    satisfiedCustomers: "مطمئن گاہک",
    citiesCovered: "شہر",
    viewAll: "سب دیکھیں",
    viewDetails: "تفصیل دیکھیں",
    viewMore: "مزید دیکھیں",
    compare: "موازنہ",
    addToWishlist: "پسندیدہ میں شامل کریں",
    removeFromWishlist: "پسندیدہ سے ہٹائیں",
    price: "قیمت",
    year: "سال",
    mileage: "مائلیج",
    fuelType: "ایندھن",
    transmission: "ٹرانسمیشن",
    color: "رنگ",
    bodyType: "گاڑی کی قسم",
    condition: "حالت",
    location: "مقام",
    city: "شہر",
    registrationCity: "رجسٹریشن شہر",
    engineCapacity: "انجن",
    doors: "دروازے",
    seatingCapacity: "نشستیں",
    assembly: "اسمبلی",
    features: "خصوصیات",
    description: "تفصیل",
    specifications: "تفصیلات",
    similarCars: "ملتی جلتی گاڑیاں",
    contactSeller: "بیچنے والے سے رابطہ",
    whatsappChat: "واٹس ایپ",
    makeInquiry: "انکوائری کریں",
    callNow: "ابھی کال کریں",
    negotiable: "قابل گفتگو",
    imported: "درآمد شدہ",
    local: "مقامی",
    filters: "فلٹر",
    clearFilters: "فلٹر صاف کریں",
    applyFilters: "فلٹر لگائیں",
    sortBy: "ترتیب",
    latest: "تازہ ترین",
    lowestPrice: "کم قیمت",
    highestPrice: "زیادہ قیمت",
    mostViewed: "سب سے زیادہ دیکھی گئی",
    minPrice: "کم از کم قیمت",
    maxPrice: "زیادہ سے زیادہ قیمت",
    minYear: "کم سال",
    maxYear: "زیادہ سال",
    allBrands: "تمام برانڈز",
    allTypes: "تمام اقسام",
    allCities: "تمام شہر",
    allConditions: "تمام حالات",
    allTransmissions: "تمام ٹرانسمیشن",
    priceRange: "قیمت کی حد",
    yearRange: "سال کی حد",
    sold: "فروخت",
    available: "دستیاب",
    reserved: "محفوظ",
    pending: "زیر التواء",
    pendingApproval: "زیر توثیق",
    draft: "مسودہ",
    scheduled: "شیڈول",
    ended: "ختم",
    active: "فعال",
    inactive: "غیر فعال",
    approved: "منظور",
    rejected: "مسترد",
    featured: "نمایاں",
    endingInText: "ختم ہونے میں",
    currentBid: "موجودہ بولی",
    startingBid: "ابتدائی بولی",
    placeBid: "بولی لگائیں",
    bidNow: "ابھی بولی لگائیں",
    reservePrice: "ریزرو قیمت",
    bidHistory: "بولی کی تاریخ",
    myBids: "میری بولیاں",
    proxyBid: "پراکسی بولی",
    depositRequired: "ڈپازٹ ضروری",
    auctionEnded: "نیلامی ختم",
    watchlist: "واچ لسٹ",
    addToWatchlist: "واچ لسٹ میں شامل کریں",
    hours: "گھنٹے",
    minutes: "منٹ",
    seconds: "سیکنڈ",
    days: "دن",
    bidIncrement: "بولی میں اضافہ",
    winner: "فاتح",
    noActiveAuctions: "اس وقت کوئی نیلامی نہیں۔",
    name: "نام",
    email: "ای میل",
    phone: "فون",
    message: "پیغام",
    subject: "موضوع",
    send: "بھیجیں",
    sending: "بھیج رہا ہے...",
    submit: "جمع کریں",
    save: "محفوظ کریں",
    saving: "محفوظ ہو رہا ہے...",
    cancel: "منسوخ",
    confirm: "تصدیق کریں",
    delete: "حذف کریں",
    edit: "ترمیم",
    add: "شامل کریں",
    update: "اپڈیٹ",
    upload: "اپلوڈ",
    brand: "برانڈ",
    model: "ماڈل",
    variant: "ورژن",
    selectBrand: "برانڈ منتخب کریں",
    selectModel: "ماڈل منتخب کریں",
    selectVariant: "ویریئنٹ منتخب کریں",
    selectYear: "سال منتخب کریں",
    selectColor: "رنگ منتخب کریں",
    selectCity: "شہر منتخب کریں",
    selectCondition: "حالت منتخب کریں",
    selectBodyType: "قسم منتخب کریں",
    selectTransmission: "ٹرانسمیشن منتخب کریں",
    selectFuelType: "ایندھن منتخب کریں",
    addImages: "تصاویر شامل کریں",
    uploadImages: "تصاویر اپلوڈ کریں",
    maxImages: "زیادہ سے زیادہ 10 تصاویر",
    generateDescription: "اے آئی تفصیل بنائیں",
    priceSuggestion: "قیمت تجویز",
    required: "ضروری",
    optional: "اختیاری",
    titleLabel: "اشتہار کا عنوان",
    chassisNumber: "چیسز نمبر",
    registrationYear: "رجسٹریشن سال",
    sellCarTitle: "اپنی گاڑی بیچیں",
    sellCarSubtitle: "پاکستان کے سب سے بڑے آٹوموٹیو مارکیٹ پلیس پر اپنی گاڑی لسٹ کریں۔",
    listingDetails: "اشتہار کی تفصیل",
    vehicleInfo: "گاڑی کی معلومات",
    contactInfo: "رابطہ معلومات",
    reviewSubmit: "جائزہ اور جمع کریں",
    basicInfo: "بنیادی معلومات",
    pricingMileage: "قیمت اور مائلیج",
    readMore: "مزید پڑھیں",
    publishedOn: "شائع کی تاریخ",
    author: "مصنف",
    categories: "زمرہ جات",
    tags: "ٹیگز",
    relatedArticles: "متعلقہ مضامین",
    latestNews: "تازہ ترین خبریں",
    allPosts: "تمام پوسٹس",
    searchArticles: "مضامین تلاش کریں...",
    shareArticle: "مضمون شیئر کریں",
    backToBlog: "بلاگ پر واپس",
    getInTouch: "ہم سے رابطہ کریں",
    contactSubtitle: "ہم آپ کی مدد کے لیے یہاں ہیں۔",
    contactInfo2: "رابطہ معلومات",
    address: "پتہ",
    openInMaps: "نقشے پر کھولیں",
    businessHours: "کاروباری اوقات",
    officeHours: "پیر تا ہفتہ: صبح 9 بجے تا شام 7 بجے",
    messageSent: "پیغام بھیج دیا گیا!",
    messageSentDesc: "ہم 24 گھنٹوں کے اندر آپ سے رابطہ کریں گے۔",
    myProfile: "میری پروفائل",
    mySavedCars: "محفوظ گاڑیاں",
    myInquiries: "میری انکوائریاں",
    notifications: "اطلاعات",
    accountSettings: "اکاؤنٹ سیٹنگز",
    profilePhoto: "پروفائل فوٹو",
    changePassword: "پاس ورڈ تبدیل کریں",
    savedSearches: "محفوظ تلاش",
    activityHistory: "سرگرمی کی تاریخ",
    dealershipDashboard: "ڈیلرشپ ڈیش بورڈ",
    inventoryManagement: "انوینٹری مینجمنٹ",
    addNewCar: "نئی گاڑی شامل کریں",
    editListing: "اشتہار ترمیم کریں",
    deleteListing: "اشتہار حذف کریں",
    leadsAndCRM: "لیڈز اور سی آر ایم",
    salesTransactions: "فروخت",
    teamManagement: "ٹیم مینجمنٹ",
    analytics: "تجزیہ",
    activityLog: "سرگرمی لاگ",
    communication: "مواصلت",
    adminDashboard: "ایڈمن ڈیش بورڈ",
    userManagement: "صارف مینجمنٹ",
    dealershipManagement: "ڈیلرشپ مینجمنٹ",
    auctionManagement: "نیلامی مینجمنٹ",
    contentManagement: "مواد مینجمنٹ",
    vehicleDatabase: "گاڑی ڈیٹابیس",
    brandSettings: "برانڈ ترتیبات",
    seoSettings: "ایس ای او",
    themeCustomizer: "تھیم",
    testimonialsMgmt: "تعریفی کلمات",
    heroBanner: "ہیرو بینر",
    homepageSections: "ہوم پیج حصے",
    brandCarousel: "برانڈ کروسل",
    imageCompression: "تصویر کمپریشن",
    inquiryManagement: "انکوائری مینجمنٹ",
    blogManagement: "بلاگ مینجمنٹ",
    listingModeration: "اشتہار نظرثانی",
    reports: "رپورٹس",
    performance: "کارکردگی",
    contactDisplay: "رابطہ ڈسپلے",
    adminContact: "ایڈمن رابطہ",
    dealerContact: "ڈیلر رابطہ",
    vehicleDatabaseTitle: "گاڑی ڈیٹابیس مینجمنٹ",
    addBrand: "برانڈ شامل کریں",
    addModel: "ماڈل شامل کریں",
    addVariant: "ورژن شامل کریں",
    editBrand: "برانڈ ترمیم",
    editModel: "ماڈل ترمیم",
    editVariant: "ورژن ترمیم",
    deleteBrand: "برانڈ حذف",
    deleteModel: "ماڈل حذف",
    deleteVariant: "ورژن حذف",
    importJson: "JSON درآمد",
    jsonImport: "JSON درآمد",
    pasteJson: "JSON ڈیٹا پیسٹ کریں",
    importFromJson: "JSON سے درآمد",
    downloadTemplate: "ٹیمپلیٹ ڈاؤنلوڈ",
    duplicateFound: "ڈپلیکیٹ ملا",
    duplicateSkipped: "ڈپلیکیٹ رد کیے گئے",
    importSuccess: "درآمد کامیاب",
    countryOfOrigin: "ملک",
    japaneseBreands: "جاپانی برانڈز",
    chineseBrands: "چینی برانڈز",
    pakistaniBrands: "پاکستانی برانڈز",
    siteLogo: "سائٹ لوگو",
    siteFavicon: "فیویکون",
    uploadLogo: "لوگو اپلوڈ کریں",
    uploadFavicon: "فیویکون اپلوڈ کریں",
    logoPreview: "لوگو پیش نظر",
    faviconPreview: "فیویکون پیش نظارہ",
    currentLogo: "موجودہ لوگو",
    logoUpdated: "لوگو کامیابی سے اپڈیٹ ہوگیا",
    faviconUpdated: "فیویکون کامیابی سے اپڈیٹ ہوگیا",
    imageConvertedWebp: "تصویر خودکار طور پر WebP میں تبدیل ہوگئی",
    quickLinks: "فوری روابط",
    contactUs: "ہم سے رابطہ",
    followUs: "فالو کریں",
    copyright: "© 2025 XYZ آٹوموبائلز۔ جملہ حقوق محفوظ۔",
    loading: "لوڈ ہو رہا ہے...",
    noResults: "کوئی نتیجہ نہیں",
    error: "خرابی",
    retry: "دوبارہ کوشش",
    goHome: "ہوم جائیں",
    pageNotFound: "صفحہ نہیں ملا",
    backToHome: "ہوم پر واپس",
    darkMode: "ڈارک موڈ",
    lightMode: "لائٹ موڈ",
    language: "زبان",
    currency: "کرنسی",
    settings: "ترتیبات",
    profile: "پروفائل",
    help: "مدد",
    about: "ہمارے بارے میں",
    privacyPolicy: "رازداری پالیسی",
    termsOfService: "خدمات کی شرائط",
    allRightsReserved: "جملہ حقوق محفوظ",
    pkr: "روپے",
    lac: "لاکھ",
    crore: "کروڑ",
    thousand: "ہزار",
    new: "نیا",
    used: "استعمال شدہ",
    certifiedPreOwned: "تصدیق شدہ",
    petrol: "پیٹرول",
    diesel: "ڈیزل",
    hybrid: "ہائبرڈ",
    electric: "بجلی",
    automatic: "آٹومیٹک",
    manual: "مینوئل",
    cvt: "سی وی ٹی",
    sedan: "سیڈان",
    suv: "ایس یو وی",
    hatchback: "ہیچ بیک",
    van: "وین",
    truck: "ٹرک",
    coupe: "کوپے",
    convertible: "کنورٹیبل",
    wagon: "ویگن",
    testimonials: "ہمارے گاہکوں کی رائے",
    heroTitle: "پاکستان کا معروف آٹوموٹو مارکیٹ پلیس",
    footerDesc: "پاکستان کا معروف لگژری آٹوموٹو مارکیٹ پلیس۔",
  },
};

interface LanguageContextType {
  lang: Language;
  setLang: (lang: Language) => void;
  t: (key: string) => string;
}

const LanguageContext = createContext<LanguageContextType | undefined>(undefined);

const LANG_LABELS: Record<Language, string> = {
  en: 'EN', ur: 'اردو',
};

export const LANG_FULL_LABELS: Record<Language, string> = {
  en: 'English', ur: 'اردو',
};

export const LANG_FLAGS: Record<Language, string> = {
  en: '🇬🇧', ur: '🇵🇰',
};

export { LANG_LABELS };

export function LanguageProvider({ children }: { children: ReactNode }) {
  const [lang, setLangState] = useState<Language>(() => {
    const saved = localStorage.getItem('xyz_lang') as Language;
    return (saved === 'en' || saved === 'ur') ? saved : 'en';
  });

  const setLang = (newLang: Language) => {
    setLangState(newLang);
    localStorage.setItem('xyz_lang', newLang);
  };

  const t = (key: string): string => {
    return translations[lang]?.[key] ?? translations.en?.[key] ?? key;
  };

  useEffect(() => {
    document.documentElement.dir = lang === 'ur' ? 'rtl' : 'ltr';
    document.documentElement.lang = lang;
  }, [lang]);

  return (
    <LanguageContext.Provider value={{ lang, setLang, t }}>
      {children}
    </LanguageContext.Provider>
  );
}

export function useLanguage() {
  const context = useContext(LanguageContext);
  if (!context) throw new Error('useLanguage must be used within LanguageProvider');
  return context;
}
